metadata:
  name: "Ensure Dockerfile uses the specified base image and installs allowed Java, Maven, Go, Gradle, and Python versions"
  id: "CKV_DOCKERFILE_1"
  category: "BEST_PRACTICES"
  scope:
    provider: dockerfile

definition:
  - cond_type: "attribute"
    resource_types:
      - "dockerfile"
    attribute: "FROM"
    operator: "equals"
    value: "artifactory-ci.myntra.com/dockerhub/service-build-env/myntra-runner:latest"

  - cond_type: "or"
    conditions:
      - cond_type: "attribute"
        resource_types:
          - "dockerfile"
        attribute: "RUN"
        operator: "regex"
        value: "(sudo apt-get install -y openjdk-(8|11|17|21)-jdk|sudo wget .*java.*(8|11|17|21).*|sudo curl .*java.*(8|11|17|21).*)"

  - cond_type: "or"
    conditions:
      - cond_type: "attribute"
        resource_types:
          - "dockerfile"
        attribute: "RUN"
        operator: "regex"
        value: "(sudo apt-get install -y maven=3\\.(3|6|8)\\.\\*|sudo wget .*maven.*3\\.(3|6|8).*|sudo curl .*maven.*3\\.(3|6|8).*)"

  - cond_type: "or"
    conditions:
      - cond_type: "attribute"
        resource_types:
          - "dockerfile"
        attribute: "RUN"
        operator: "regex"
        value: "(sudo apt-get install -y golang-1\\.(13|17|18|20)|sudo wget .*go.*1\\.(13|17|18|20).*|sudo curl .*go.*1\\.(13|17|18|20).*)"

  - cond_type: "or"
    conditions:
      - cond_type: "attribute"
        resource_types:
          - "dockerfile"
        attribute: "RUN"
        operator: "regex"
        value: "(sudo apt-get install -y gradle=1\\.(3|7|10)|sudo apt-get install -y gradle=2\\.9|sudo apt-get install -y gradle=3\\.1|sudo wget .*gradle.*(1\\.3|1\\.7|1\\.10|2\\.9|3\\.1).*|sudo curl .*gradle.*(1\\.3|1\\.7|1\\.10|2\\.9|3\\.1).*)"

  - cond_type: "or"
    conditions:
      - cond_type: "attribute"
        resource_types:
          - "dockerfile"
        attribute: "RUN"
        operator: "regex"
        value: "(sudo apt-get install -y python(2.7|3.6|3.8|3.9)|sudo wget .*python.*(2.7|3.6|3.8|3.9).*|sudo curl .*python.*(2.7|3.6|3.8|3.9).*)"
