name: Checkov Dockerfile Scan

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Checkov with the custom policy
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./cosmos 
          external_checks_dir: .github/checkov/custom_policies
          quiet: false
          soft_fail: false
          framework: dockerfile
