name: Dockerfile validation

on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dockerfile validation
        uses: NiranjanOrgGround/Dockerfile-validation@main
        env:
          STANDARDS_PATH: managed_files/standards.json
          DOCKERFILE_PATH: cosmos/Dockerfile

      - name: Build the Docker image
        run: echo "Building the Docker Image..."
